version: 2.0.0.{build}
image: Visual Studio 2019
dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
install:
    - ps: Install-Product node LTS x64
    - choco install firefox
    - choco install googlechrome
cache: '%LOCALAPPDATA%\Yarn'
environment:
    RETURN_TEST_WAIT_TIME: 30
build_script:
    - cmd: build.cmd --target=Publish --verbosity=verbose
after_build:
    - ps: Get-ChildItem ./build/publish/* -File | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    - ps: Get-ChildItem ./build/ -File | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
#before_test:
#    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
test_script:
    - cmd: build.cmd --target=Test
on_finish:
    - ps: Compress-Archive -Path .\build\testresults -DestinationPath .\build\testresults-all.zip
    - ps: Push-AppveyorArtifact .\build\testresults-all.zip -FileName "testresults-all.zip"
deploy: off
artifacts:
    - path: build\testresults\*.trx
      name: test logs
    - path: build\testresults\**
      name: test artifacts
      type: zip
